//controller for user registration
import jwt from "jsonwebtoken";
import User from "../modals/User.js";
import bcrypt from "bcrypt";
import Resume from "../modals/Resume.js";

const generateToken = (userId) => {
  const token = jwt.sign({ userId }, process.env.JWT_SECRET, {
    expiresIn: "7d",
  });
  return token;
};
export const registerUser = async (req, res) => {
  try {
    const { name, email, password } = req.body;
    //check if required field are present
    if (!name || !email || !password) {
      return res.status(400).json({ message: "Missing required fields" });
    }
    //check if user already exits
    const user = await User.findOne({ email });
    if (user) {
      return res.status(400).json({ message: "User already exists" });
    }
    //create new user
    const hashedPassword = await bcrypt.hash(password, 10);
    const newUser = await User.create({
      name,
      email,
      password: hashedPassword,
    });
    //return succeess message
    const token = generateToken(newUser._id); //auto generated by mongodb
    newUser.password = undefined;
    return res
      .status(201)
      .json({ message: "User created successfully", token, user: newUser });
  } catch (error) {
    return res.status(400).json({ message: error.message });
  }
};

//controller for user login
// /POST: /api/users/register

export const loginUser = async (req, res) => {
  try {
    const { email, password } = req.body;
    //check if user already exits
    const user = await User.findOne({ email });
    if (!user) {
      return res.status(400).json({ message: "Invalid email or password" });
    }

    //check if password correct
    if (!user.comparePassword) {
      return res.status(400).json({ message: "Invalid email or password" });
    }
    //return succeess message
    const token = generateToken(user._id); //auto generated by mongodb
    user.password = undefined;
    return res.status(200).json({ message: "Login successfully", token, User });
  } catch (error) {
    return res.status(400).json({ message: error.message });
  }
};

//controller for getting user by id

//GET:/api/users/data

export const getUserById = async (req, res) => {
  try {
    const userId = req.userId;
    //check if user exist
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }
    //return user
    user.password = undefined;
    return res.status(200).json({ User });
  } catch (error) {
    return res.status(400).json({ message: error.message });
  }
};

//controller for getting user resumes
//GET: /api/users/resumes
export const getUserResumes = async (req, res) => {
  try {
    const userId = req.userId;
    //return user resume
    const resumes = await Resume.find({ userId });
    return response.status(200).json({ resumes });
  } catch (error) {
    return res.status(400).json({ message: error_message });
  }
};
